services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      

  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./data:/entrapeer/data
      
  worker:
    build: .
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./data:/entrapeer/data
  
  fetch-corporates:
    build: .
    command: ["python", "fetch_top_ranked_corporates.py"]
    depends_on:
      - web
    volumes:
      - ./data:/entrapeer/data